---
- name: install package
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ suse_useful_packages }}"

- name: start open-vm-tools
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - vgauthd
    - vmtoolsd
